version: "3.8"

services:
  html2pdf2:
    container_name: html2pdf2
    build:
      context: .
    restart: unless-stopped
    environment:
      PORT: 3000
      EXECUTABLE_PATH: /usr/bin/chromium
      SNAPSHOT_HOST: /usr/bin/chromium
    ports:
      - 3000:3000
